(()=>{
async function openAdmin(){
 const email=(sessionStorage.getItem('class_admin_email')||prompt('请输入管理员邮箱')||'').trim().toLowerCase();if(email!=='3422306811@qq.com'){alert('邮箱不正确，无法进入管理员。');return}sessionStorage.setItem('class_admin_email',email);
 const src=await fetch('email-admin.js').then(r=>r.text()),m=src.match(/const U='([^']+)',K='([^']+)'/);if(!m){alert('管理员配置读取失败');return}const s=window.supabase.createClient(m[1],m[2]);
 const {data:ps,error}=await s.from('posts').select('id,user_name,content,pinned,hidden,created_at,post_comments(id,user_name,content)').order('created_at',{ascending:false}).limit(100);if(error){alert('读取动态失败：'+error.message);return}
 document.getElementById('admin-panel')?.remove();document.body.style.overflow='auto';document.documentElement.style.overflow='auto';const p=document.createElement('div');p.id='admin-panel';p.innerHTML='<div class="amask"><div class="abox"><header><b>班级朋友圈管理</b><button id="ax">×</button></header><main></main></div></div>';
 const st=document.createElement('style');st.textContent=`#admin-panel{position:absolute!important;top:0;left:0;width:100%;min-height:100vh;z-index:100000}#admin-panel .amask{position:relative!important;width:100%;min-height:100vh;background:#000b;display:block!important;padding:10px!important;overflow:visible!important}#admin-panel .abox{width:min(760px,100%)!important;min-height:calc(100vh - 20px)!important;height:auto!important;margin:0 auto!important;background:#06192d!important;border:1px solid #167ac1;border-radius:18px!important;overflow:visible!important;color:#dff4ff}#admin-panel .abox header{position:sticky!important;top:0!important;z-index:5!important;padding:16px 18px!important;border-bottom:1px solid #123a5d!important;display:flex!important;justify-content:space-between!important;font-size:18px!important;background:#071d33!important}#admin-panel .abox header button{border:0;background:none;font-size:28px;color:#dff4ff}#admin-panel .aitem{padding:15px;border-bottom:1px solid #12304a}#admin-panel .abtn{border:0;border-radius:9px;padding:8px 12px;margin:4px;background:#0b2b45;color:#9fd7f1}#admin-panel .danger{color:#ff7897;background:#4b1527}#admin-panel .atext{white-space:pre-wrap;margin:8px 0;color:#9ab7c9}#admin-panel .ac{margin:8px 0 0 12px;padding:8px;background:#041321;border-radius:8px}#admin-panel .ac button{float:right;border:0;background:none;color:#ff6c8f}@media(max-width:700px){#admin-panel .amask{padding:0!important}#admin-panel .abox{width:100%!important;border-radius:0!important;border-left:0!important;border-right:0!important}}`;
 document.head.appendChild(st);document.body.appendChild(p);const main=p.querySelector('main');(ps||[]).sort((a,b)=>(Number(b.pinned)-Number(a.pinned))||new Date(b.created_at)-new Date(a.created_at)).forEach(x=>{const d=document.createElement('section');d.className='aitem';d.innerHTML='<b></b><div class="atext"></div><div class="acts"></div>';d.querySelector('b').textContent=(x.user_name||'匿名')+(x.pinned?'  📌已置顶':'');d.querySelector('.atext').textContent=x.content||'';const a=d.querySelector('.acts');[['pin',x.pinned?'取消置顶':'置顶'],['hide',x.hidden?'恢复显示':'隐藏'],['del','删除动态']].forEach(([k,t])=>{const b=document.createElement('button');b.className='abtn '+(k==='del'?'danger':'');b.textContent=t;b.onclick=async()=>{if(k==='del'&&!confirm('确定删除这条动态吗？'))return;const field=k==='pin'?'pinned':'hidden';const r=k==='del'?await s.from('posts').delete().eq('id',x.id):await s.from('posts').update({[field]:!x[field]}).eq('id',x.id);if(r.error)alert('操作失败：'+r.error.message);else openAdmin()};a.appendChild(b)});(x.post_comments||[]).forEach(c=>{const q=document.createElement('div');q.className='ac';const t=document.createElement('span');t.textContent=(c.user_name||'匿名')+'：'+(c.content||'');q.appendChild(t);const b=document.createElement('button');b.textContent='删除评论';b.onclick=async()=>{if(!confirm('确定删除这条评论吗？'))return;const r=await s.from('post_comments').delete().eq('id',c.id);if(r.error)alert('删除失败：'+r.error.message);else openAdmin()};q.appendChild(b);d.appendChild(q)});main.appendChild(d)});p.querySelector('#ax').onclick=()=>{p.remove();document.body.style.overflow='auto';document.documentElement.style.overflow='auto'};
}
function bind(){document.getElementById('class-admin-modal')?.remove();const b=document.getElementById('class-admin-btn');if(b)b.onclick=openAdmin;const tabs=document.querySelectorAll('#community .tabs span');tabs.forEach((tab,i)=>{tab.onclick=()=>{tabs.forEach(t=>t.classList.remove('active'));tab.classList.add('active');const posts=[...document.querySelectorAll('#moment-feed .moment-post')];posts.forEach(p=>p.style.display='');if(i===1)posts.forEach(p=>{if(!p.querySelector('.moment-badge:nth-of-type(2)'))p.style.display='none'});if(i===2){const feed=document.getElementById('moment-feed');posts.sort((a,b)=>{const ta=a.querySelector('time')?.textContent||'';const tb=b.querySelector('time')?.textContent||'';return tb.localeCompare(ta)}).forEach(p=>feed.appendChild(p))}})});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,500));else setTimeout(bind,500);setTimeout(bind,3500);
})();