(()=>{
const U='https://uvmojhlpmrpjpfcupwbk.supabase.co',K='sb_publishable_4GCp4gl6N91d_J9z_VuooA_JVNYZCVG',B='class-resources';
const H={apikey:K,Authorization:'Bearer '+K};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>{if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(1)+' MB'};
async function load(){const box=document.getElementById('resource-files');if(!box)return;box.innerHTML='<div class="resource-empty">正在加载共享文件…</div>';try{const r=await fetch(U+'/storage/v1/object/list/'+B,{method:'POST',headers:{...H,'Content-Type':'application/json'},body:JSON.stringify({prefix:'',limit:100,sortBy:{column:'created_at',order:'desc'}})});const data=await r.json();if(!r.ok)throw Error(data.message||data.error||('HTTP '+r.status));const files=(data||[]).filter(x=>x.name);if(!files.length){box.innerHTML='<div class="resource-empty">还没有文件，上传第一个吧 📚</div>';return}box.innerHTML=files.map(f=>{const url=U+'/storage/v1/object/public/'+B+'/'+encodeURIComponent(f.name);return `<div class="resource-file"><div class="resource-file-icon">📄</div><div class="resource-file-info"><b>${esc(f.name)}</b><small>${fmt(f.metadata?.size||0)}</small></div><a href="${esc(url)}" target="_blank" rel="noopener" download>下载</a></div>`}).join('')}catch(e){box.innerHTML='<div class="resource-empty">读取失败：'+esc(e.message)+'</div>'}}
async function upload(){const input=document.getElementById('resource-input'),status=document.getElementById('resource-status'),btn=document.getElementById('resource-upload');const files=[...(input?.files||[])];if(!files.length){alert('请选择要上传的文件');return}if(files.some(f=>f.size>50*1024*1024)){alert('单个文件不能超过 50MB');return}btn.disabled=true;status.textContent='正在上传…';try{for(const f of files){const ext=(f.name.match(/\.[A-Za-z0-9]+$/)||[''])[0].toLowerCase();const path='file_'+Date.now()+'_'+Math.random().toString(36).slice(2,10)+ext;const r=await fetch(U+'/storage/v1/object/'+B+'/'+encodeURIComponent(path),{method:'POST',headers:{...H,'Content-Type':f.type||'application/octet-stream','x-upsert':'false'},body:f});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.message||data.error||data.error_description||('HTTP '+r.status))}status.textContent='上传成功！';input.value='';load()}catch(e){status.textContent='上传失败：'+e.message;alert('文件上传失败：'+e.message)}finally{btn.disabled=false}}
function init(){const b=document.getElementById('resource-upload');if(!b)return;b.onclick=upload;load()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
