document.addEventListener("DOMContentLoaded",()=>{
const reveal=()=>document.querySelectorAll(".reveal").forEach(el=>{if(el.getBoundingClientRect().top<window.innerHeight*.88)el.classList.add("visible")});window.addEventListener("scroll",reveal,{passive:true});reveal();document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener("click",e=>{const t=document.querySelector(a.getAttribute("href"));if(t){e.preventDefault();t.scrollIntoView({behavior:"smooth"})}}));const date=document.getElementById("date");if(date){const d=new Date();date.textContent=d.toLocaleDateString("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit",weekday:"short"})}const menu=document.querySelector(".menu");const nav=document.querySelector("nav");if(menu)menu.addEventListener("click",()=>nav.classList.toggle("open"));

const box=document.getElementById("utterances");
if(!box||!window.supabase)return;
box.innerHTML=`<div class="moments"><div class="moment-compose"><input id="moment-name" maxlength="30" placeholder="你的昵称"><textarea id="moment-content" maxlength="1000" placeholder="分享一下班级里的新鲜事…"></textarea><div class="moment-tools"><label class="moment-image">🖼️ 图片 <input id="moment-image" type="file" accept="image/jpeg,image/png,image/webp,image/gif"></label><button id="moment-publish">发布动态</button></div><div id="moment-status"></div></div><div class="moment-feed" id="moment-feed"><div class="moment-loading">正在加载班级动态…</div></div></div>`;
const client=window.supabase.createClient("https://uvmojhlpmrpjpfcupwbk.supabase.co","sb_publishable_4GCp4gl6N91d_J9z_VuooA_JVNYZCVG");
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const fmt=s=>new Date(s).toLocaleString("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"});
const cid=()=>{let x=localStorage.getItem("class_moments_client");if(!x){x=crypto.randomUUID();localStorage.setItem("class_moments_client",x)}return x};
const status=t=>document.getElementById("moment-status").textContent=t||"";
async function load(){const feed=document.getElementById("moment-feed");const {data,error}=await client.from("posts").select("id,user_name,content,image_url,created_at,post_likes(client_id),post_comments(id,user_name,content,created_at)").order("created_at",{ascending:false}).limit(30);if(error){feed.innerHTML='<div class="moment-empty">暂时无法加载动态，请稍后再试。</div>';return}if(!data.length){feed.innerHTML='<div class="moment-empty">还没有动态，来发第一条吧 👋</div>';return}feed.innerHTML=data.map(p=>{const comments=(p.post_comments||[]).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));const liked=(p.post_likes||[]).some(x=>x.client_id===cid());return `<article class="moment-post"><div class="moment-avatar">${esc((p.user_name||"同学").slice(0,1))}</div><div class="moment-main"><div class="moment-head"><b>${esc(p.user_name)}</b><time>${fmt(p.created_at)}</time></div><p>${esc(p.content).replace(/\n/g,"<br>")}</p>${p.image_url?`<img class="moment-photo" src="${esc(p.image_url)}" alt="班级分享图片" loading="lazy">`:""}<div class="moment-actions"><button class="moment-like ${liked?"liked":""}" data-id="${p.id}">❤️ ${p.post_likes?.length||0}</button><span>💬 ${comments.length}</span></div><div class="moment-comments">${comments.map(c=>`<div><b>${esc(c.user_name)}</b><span>${esc(c.content)}</span></div>`).join("")}<div class="moment-comment-form"><input data-comment-name="${p.id}" maxlength="30" placeholder="昵称"><input data-comment-content="${p.id}" maxlength="300" placeholder="写下你的评论…"><button data-comment="${p.id}">发送</button></div></div></div></article>`}).join("");feed.querySelectorAll(".moment-like").forEach(b=>b.onclick=()=>like(b.dataset.id));feed.querySelectorAll("[data-comment]").forEach(b=>b.onclick=()=>comment(b.dataset.comment));}
async function like(id){const existing=await client.from("post_likes").select("id").eq("post_id",id).eq("client_id",cid()).maybeSingle();if(existing.data){await client.from("post_likes").delete().eq("id",existing.data.id)}else{await client.from("post_likes").insert({post_id:id,client_id:cid()})}load()}
async function comment(id){const name=document.querySelector(`[data-comment-name="${id}"]`).value.trim();const content=document.querySelector(`[data-comment-content="${id}"]`).value.trim();if(!name||!content)return alert("请填写昵称和评论内容");const {error}=await client.from("post_comments").insert({post_id:id,user_name:name,content});if(error)alert("评论失败，请稍后再试");else load()}
document.getElementById("moment-publish").onclick=async()=>{const name=document.getElementById("moment-name").value.trim();const content=document.getElementById("moment-content").value.trim();const file=document.getElementById("moment-image").files[0];if(!name||!content){status("请填写昵称和动态内容");return}if(file&&file.size>6291456){status("图片不能超过 6MB");return}status("正在发布…");let image_url=null;if(file){const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const path=`${Date.now()}-${crypto.randomUUID()}.${ext}`;const up=await client.storage.from("moment-images").upload(path,file,{contentType:file.type});if(up.error){status("图片上传失败，请换一张图片再试");return}image_url=client.storage.from("moment-images").getPublicUrl(path).data.publicUrl}const {error}=await client.from("posts").insert({user_name:name,content,image_url});if(error){status("发布失败，请稍后再试");return}document.getElementById("moment-content").value="";document.getElementById("moment-image").value="";status("发布成功！");load()};load();
});